# Generated by Django 2.0.4 on 2018-04-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagegallery', '0002_auto_20180419_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
