version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: ./start.sh
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DEBUG=false
      - PRODUCTION=true
    ports:
      - "5000:5000"

  db:
    image: postgres

    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
