# Generated by Django 2.0.4 on 2018-04-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('creator', models.IntegerField()),
                ('images', models.ManyToManyField(to='images.Image')),
            ],
        ),
    ]
