# Generated by Django 2.0.4 on 2018-04-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('uploaded', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('uploader', models.IntegerField()),
                ('pic', models.ImageField(default='images/default_game_img.png', upload_to='images/')),
            ],
        ),
    ]
