# Generated by Django 2.0.4 on 2018-06-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20180527_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='pic',
            field=models.ImageField(default='images/default_image.png', upload_to='images/'),
        ),
    ]
