# Generated by Django 2.0.4 on 2018-06-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_image_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='compressed_pic',
            field=models.ImageField(default='images/default_image.png', upload_to='images/'),
        ),
    ]
